name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x
      - run: deno test --coverage
      - run: deno coverage --lcov --output=cov.lcov
      - uses: livewing/lcov-job-summary@v1.2.0
        with:
          lcov: cov.lcov
      - uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: cov.lcov
          min_coverage: 95
      - run: |
          echo '{"name": "@jonasgrunert/subrouter","version": "${{ github.ref_name }}","license": "MIT","exports": "./router.ts"}' > jsr.json
      - run: npx jsr publish
