name: Publish

on:
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x
      - run: deno test --coverage
      - run: deno coverage --lcov --output=cov.lcov
      - uses: livewing/lcov-job-summary@v1.2.0
        with:
          lcov: cov.lcov
      - run: |
          COVERAGE=$(deno coverage | grep "total:" | grep -o '[0-9]\+\.[0-9]\+')
          if (( $(echo "$COVERAGE < 95" | bc -l) )); then
            echo "Test coverage is below 95%: $COVERAGE%"
            exit 1
          fi
